name: hue-qt
base: core20
version: '1.0.0'
summary: Control Philips Hue lights and syncbox
description: |
  This is a project for controlling Philips Hue Bridge and Philips Hue HDMI Syncbox. The application uses the QT framework and it targets Linux.

grade: stable
confinement: devmode

architectures:
  - build-on: amd64
    run-on: amd64

environment:
  SNAP_DESKTOP_RUNTIME: $SNAP/qt515-core20

apps:
  hue-qt:
    command: bin/desktop-launch $SNAP/usr/bin/hue-qt
    desktop: usr/share/applications/hue-qt.desktop

plugs:
  qt515-core20:
    interface: content
    target: $SNAP/qt515-core20
    default-provider: qt515-core20

parts:
  hue-qt:
    plugin: cmake
    source: .
    build-packages: [qt515base, qt515tools]

